name: uv_monitor

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with pytest
        run: make test

      - name: Archive code testing results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: |
            output/test/test-coverage.xml
            report.xml
          retention-days: 1

      - name: Lint
        run: |
          make fmt black-args=--check isort-args='--check-only --diff'
          make lint
